[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#f0f4fa'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#e0e8f6'

# Color used for almost all text
textColor = '#070808'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"